[prop]
id = "my_module"
version = "1.0.0"
versionCode = 1
author = "Author"

[prop.name]
en = "My Module"

[prop.description]
en = "A module description"

[kam]
module_type = "Template"

[kam.tmpl.variables]
