[prop]
id = "Kam"
version = "1.0.0"
versionCode = 1763053528962
author = "LIghtJUNction (LIghtJUNction.me@gmail.com)"
updateJson = "https://raw.githubusercontent.com/MemDeco-WG/Kam/main/update.json"

[prop.name]
en = "Kam"
ja = "Kam"
ko = "Kam"
zh-CN = "Kam"
zh-TW = "Kam"

[prop.description]
en = "A kam module"
ja = "kamモジュール"
ko = "kam 모듈"
zh-CN = "一个kam模块"
zh-TW = "一個kam模組"

[mmrl.repo]
license = "MIT"
license_file = "LICENSE"
homepage = ""
readme = ""
readme_file = "README.md"
changelog = ""
changelog_file = "CHANGELOG.md"
screenshots = []
categories = []
keywords = []
maintainers = []
repository = ""
documentation = ""
issues = ""
funding = ""
support = ""
donate = ""
cover = ""
icon = ""
devices = []
arch = []
require = []
antifeatures = []
max_num = 0
min_api = 0
max_api = 0
verified = false
features = []

[mmrl.repo.note]
title = ""
message = ""

[mmrl.repo.manager.magisk]
devices = []
arch = []
require = []

[mmrl.repo.manager.kernelsu]
devices = []
arch = []
require = []

[mmrl.repo.manager.apatch]
devices = []
arch = []
require = []

[mmrl.repo.options.archive]
compression = ""

[kam]
min_api = 0
max_api = 0
supported_arch = []
conflicts = []
module_type = "kam"

[kam.dependency]
kam = []
dev = []

[kam.build]
target_dir = "dist"
output_file = "{{id}}-{{versionCode}}"
pre_build = 'echo "pre build..."'
post_build = 'echo "post build..."'

[kam.tmpl]
used_template = "kam_template"

[kam.tmpl.variables]

[kam.lib]
provides = []

[kam.workspace]
members = [
    ".",
    "tmpl/kam_template",
    "tmpl/tmpl_template",
    "tmpl/repo_template",
    "tmpl/venv_template"
]

[tool]

[tmpl.variables]
