[prop]
id = "venv_template"
version = "1.0.0"
versionCode = 1762852219062
author = "Author"

[prop.name]
en = "kam_venv"

[prop.description]
en = "kam_module virtual environment"

[mmrl.repo]
license = "LICENSE"
homepage = ""
readme = "README.md"
screenshots = []
categories = []
keywords = []
maintainers = []
repository = ""
documentation = ""
issues = ""
funding = ""
support = ""
donate = ""
cover = ""
icon = ""
devices = []
arch = []
require = []
antifeatures = []
max_num = 0
min_api = 0
max_api = 0
verified = false
features = []

[mmrl.repo.note]
title = ""
message = ""

[mmrl.repo.manager.magisk]
devices = []
arch = []
require = []

[mmrl.repo.manager.kernelsu]
devices = []
arch = []
require = []

[mmrl.repo.manager.apatch]
devices = []
arch = []
require = []

[mmrl.repo.options.archive]
compression = ""

[kam]
min_api = 0
max_api = 0
supported_arch = []
conflicts = []
module_type = "template"

[kam.dependency]
kam = []
dev = []

[kam.build]
target_dir = "../../src/assets/tmpl"
output_file = "venv_template"
pre_build = 'echo "venv pre build..."'
post_build = 'echo "venv post build..."'


[kam.tmpl.variables]

[kam.lib]
provides = []
