[prop]
id = "kam_template"
version = "1.0.0"
versionCode = 1762776344578
author = "Author"

[prop.name]
en = "My Module"

[prop.description]
en = "A module description"

[mmrl.repo]
license = "LICENSE"
homepage = "https://github.com/example/repo"
readme = "README.md"
categories = ["Kam"]
keywords = ["android", "root", "module"]

[kam]
module_type = "Template"

[kam.tmpl.variables]
