[prop]
id = "kam_template"
version = "0.1.0"
versionCode = 1762850845388
author = "Author (author@example.com)"

[prop.name]
en = "{{project_name}}"

[prop.description]
en = "{{description}}"

[mmrl.repo]
license = "MIT"
license_file = "LICENSE"
homepage = ""
support = ""
donate = ""
cover = ""
icon = ""
readme = ""
readme_file = "README.md"
changelog = ""
changelog_file = "CHANGELOG.md"
screenshots = []
categories = []
keywords = []
maintainers = []
devices = []
arch = []
require = []
antifeatures = []
max_num = 0
min_api = 0
max_api = 0
verified = false
features = []

[mmrl.repo.note]
title = ""
message = ""

[mmrl.repo.manager.magisk]
devices = []
arch = []
require = []

[mmrl.repo.manager.kernelsu]
devices = []
arch = []
require = []

[mmrl.repo.manager.apatch]
devices = []
arch = []
require = []

[mmrl.repo.options.archive]
compression = ""

[kam]
min_api = 0
max_api = 0
supported_arch = []
conflicts = []
module_type = "template"


[kam.dependency]
kam = []
dev = []

[kam.build]
target_dir = "../../src/assets/tmpl"
output_file = "kam_template"
pre_build = 'echo "pre build..."'
post_build = 'echo "post build..."'

[kam.tmpl.variables]

[tool]

[tmpl.variables]
