[prop]
id = "tmpl_1"
version = "1.0.0"
versionCode = 1762771971456
author = "Author"

[prop.name]
en = "My Module"

[prop.description]
en = "A module description"

[kam]
module_type = "Template"

[kam.tmpl.variables]
