[prop]
id = "kam_template"
version = "0.1.0"
versionCode = 1762850845388
author = "Author"

[prop.name]
en = "kam_template"

[prop.description]
en = "kam_template: the kam module template."

[mmrl.repo]
license = "LICENSE"
homepage = ""
readme = "README.md"
screenshots = []
categories = []
keywords = []
maintainers = []
repository = ""
documentation = ""
issues = ""
funding = ""
support = ""
donate = ""
cover = ""
icon = ""
devices = []
arch = []
require = []
antifeatures = []
max_num = 0
min_api = 0
max_api = 0
verified = false
features = []

[mmrl.repo.note]
title = "{{mmrl.repo.note.title}}"
message = ""

[mmrl.repo.manager.magisk]
devices = []
arch = []
require = []

[mmrl.repo.manager.kernelsu]
devices = []
arch = []
require = []

[mmrl.repo.manager.apatch]
devices = []
arch = []
require = []

[mmrl.repo.options.archive]
compression = ""

[kam]
min_api = 0
max_api = 0
supported_arch = []
conflicts = []
module_type = "kam"

[kam.tmpl.variables]
[kam.tmpl.variables.hello_kam]
var_type = "string"
required = true
default = ""
note = "请使用 --var hello_kam=<值> 提供任意文本即可，例如: --var hello_kam=hello!"
help = "本配置供测试使用"
example = "hello!"
choices = []

[kam.tmpl.variables."mmrl.repo.note.title"]
var_type = "string"
required = true
default = "Default Title"
note = "请使用 --var mmrl.repo.note.title=<值> 提供标题，例如: --var mmrl.repo.note.title=My Title"
help = "仓库注释的标题"
example = "My Title"
choices = []



[kam.dependency]
kam = []
dev = []

[kam.build]
target_dir = "../../src/assets/tmpl"
output_file = "kam_template"
pre_build = 'echo "pre build..."'
post_build = 'echo "post build..."'

[kam.lib]
provides = []
