[prop]
id = "lib_template"
version = "1.0.0"
versionCode = 1762776394452
author = "Author"

[prop.name]
en = "My Module"

[prop.description]
en = "A module description"


[mmrl.repo]
license = "LICENSE"
homepage = "https://github.com/example/repo"
readme = "README.md"
categories = ["Kam"]
keywords = ["android", "root", "module"]

[kam]
module_type = "Library"

[kam.tmpl.variables]
